name: Metrics
on:
  # Run every day at 6AM
  schedule: [{cron: "0 6 * * *"}]
  # Allow manual runs
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Basic setup
          user: suhaz786
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Dubai

          # Plugins (choose what to display)
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_followup: yes
